#!/usr/bin/env bash
# Generated by cgraf78/actions release-installer. Do not edit.
#
# This file is deliberately self-contained. A user may download only install.sh,
# so runtime behavior cannot depend on the actions checkout that generated it.

set -euo pipefail
export LC_ALL=C
umask 077

release_repo='cgraf78/termnav'
release_slug='termnav'
release_asset_name='termnav'
release_binary='termnav'
release_binary_dest='bin/termnav'
release_manpage_path='man/man1/termnav.1'
owner_marker='cgraf78/actions release-installer v1'

scratch=
lock_dir=
lock_held=0
incoming=
next_current=
stable_root=
stable_target=
command_link=
command_target=
man_link=
man_target=
published_stable=0
published_command=0
published_man=0

rollback_published_link() {
  local path=$1 target=$2 published=$3

  [[ "$published" -eq 1 ]] || return 0
  # Remove only the exact link this invocation intended to publish. If another
  # process changed the path after publication, preserving that newer value is
  # safer than treating the whole destination directory as installer-owned.
  if [[ -L "$path" && $(readlink "$path") == "$target" ]]; then
    rm -f "$path" 2>/dev/null || true
  fi
}

cleanup() {
  status=$?
  trap - EXIT
  # Public links are all-or-nothing. Destination preflight catches ordinary
  # collisions, but a late filesystem or ln failure can still occur after an
  # earlier link was created. Roll back only links first published by this
  # invocation, in reverse order; the private verified release remains staged
  # so a retry need not redownload or trust incomplete bytes.
  rollback_published_link "$man_link" "$man_target" "$published_man"
  rollback_published_link "$command_link" "$command_target" "$published_command"
  rollback_published_link "$stable_root" "$stable_target" "$published_stable"
  if [[ -n "$incoming" && -d "$incoming" && ! -L "$incoming" ]]; then
    rm -rf "$incoming"
  fi
  if [[ -n "$next_current" && -L "$next_current" ]]; then
    rm -f "$next_current"
  fi
  if [[ "$lock_held" -eq 1 && -n "$lock_dir" ]]; then
    rmdir "$lock_dir" 2>/dev/null || true
  fi
  if [[ -n "$scratch" && -d "$scratch" && ! -L "$scratch" ]]; then
    rm -rf "$scratch"
  fi
  exit "$status"
}
trap cleanup EXIT

die() {
  printf 'install.sh: %s\n' "$*" >&2
  exit 1
}

sha256_file() {
  local file=$1 output

  # SHA-256 is already part of the archive trust boundary, so reuse it for
  # idempotence instead of adding a hidden dependency on diffutils' `cmp`.
  # Minimal Arch and other bootstrap environments may provide one checksum
  # implementation but no general-purpose byte-comparison utility.
  if command -v sha256sum >/dev/null 2>&1; then
    output=$(sha256sum "$file") || die "cannot hash file: $file"
  else
    command -v shasum >/dev/null 2>&1 ||
      die 'neither sha256sum nor shasum is available'
    output=$(shasum -a 256 "$file") || die "cannot hash file: $file"
  fi
  printf '%s\n' "${output%% *}"
}

usage() {
  cat <<EOF
usage: install.sh [options]

Install a published $release_repo release archive.

Options:
  --version TAG      install an exact published release
  --archive PATH     install a local release archive instead of downloading
  --checksum PATH    checksum for --archive (default: PATH.sha256)
  --data-home PATH   archive-root parent (default: XDG_DATA_HOME or ~/.local/share)
  --bin-dir PATH     public command directory (default: ~/.local/bin)
  --man-dir PATH     manual-page directory (default: DATA_HOME/man/man1)
  -h, --help         show this help
EOF
}

require_value() {
  option=$1
  value=${2:-}
  [[ -n "$value" ]] || {
    printf 'install.sh: %s requires a value\n' "$option" >&2
    usage >&2
    exit 2
  }
}

archive=
checksum=
requested_version=
data_home=
bin_dir=
man_dir=
archive_is_private=0

while [[ $# -gt 0 ]]; do
  case $1 in
    -h | --help)
      usage
      exit 0
      ;;
    --version)
      require_value "$1" "${2:-}"
      requested_version=$2
      shift 2
      ;;
    --archive)
      require_value "$1" "${2:-}"
      archive=$2
      shift 2
      ;;
    --checksum)
      require_value "$1" "${2:-}"
      checksum=$2
      shift 2
      ;;
    --data-home)
      require_value "$1" "${2:-}"
      data_home=$2
      shift 2
      ;;
    --bin-dir)
      require_value "$1" "${2:-}"
      bin_dir=$2
      shift 2
      ;;
    --man-dir)
      require_value "$1" "${2:-}"
      man_dir=$2
      shift 2
      ;;
    *)
      printf 'install.sh: unknown option: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

[[ -n ${HOME:-} ]] || die 'HOME is not set'

uname_s=$(uname -s 2>/dev/null) || die 'cannot determine operating system'
uname_m=$(uname -m 2>/dev/null) || die 'cannot determine architecture'
uname_o=$(uname -o 2>/dev/null || true)

case "$uname_m" in
  x86_64 | amd64) release_arch=x86_64 ;;
  arm64 | aarch64) release_arch=aarch64 ;;
  *) die "unsupported architecture: $uname_m" ;;
esac

case "$uname_s" in
  Darwin)
    release_platform=macos-$release_arch
    ;;
  Linux)
    if [[ "$uname_o" == Android || -n ${ANDROID_ROOT:-} ]]; then
      [[ "$release_arch" == aarch64 ]] ||
        die "no published release for android-$release_arch"
      release_platform=android-aarch64
    else
      release_platform=linux-$release_arch-musl
    fi
    ;;
  *)
    die "unsupported operating system: $uname_s"
    ;;
esac

if [[ -z "$data_home" ]]; then
  data_home=${XDG_DATA_HOME:-$HOME/.local/share}
fi
if [[ -z "$bin_dir" ]]; then
  if [[ "$release_platform" == android-* ]]; then
    [[ -n ${PREFIX:-} ]] || die 'PREFIX is not set for Android/Termux'
    bin_dir=$PREFIX/bin
  else
    bin_dir=$HOME/.local/bin
  fi
fi
if [[ -z "$man_dir" ]]; then
  if [[ "$release_platform" == android-* ]]; then
    [[ -n ${PREFIX:-} ]] || die 'PREFIX is not set for Android/Termux'
    man_dir=$PREFIX/share/man/man1
  else
    man_dir=$data_home/man/man1
  fi
fi

normalize_destination() {
  path=$1
  label=$2

  case "$path" in
    /*) ;;
    *) die "$label must be absolute: $path" ;;
  esac
  case "$path" in
    /) die "$label must not be the filesystem root" ;;
    *//* | */./* | */. | */../* | */..)
      die "$label must not contain empty or dot path segments: $path"
      ;;
  esac
  while [[ "$path" == */ ]]; do
    path=${path%/}
  done
  printf '%s\n' "$path"
}

data_home=$(normalize_destination "$data_home" 'data home')
bin_dir=$(normalize_destination "$bin_dir" 'command directory')
man_dir=$(normalize_destination "$man_dir" 'manual-page directory')

cgraf_root=$data_home/cgraf78
control_root=$cgraf_root/.$release_slug-standalone
stable_root=$cgraf_root/$release_slug
stable_target=.$release_slug-standalone/current
command_link=$bin_dir/$release_binary
command_target=$stable_root/$release_binary_dest
man_link=$man_dir/$release_binary.1
man_target=$stable_root/$release_manpage_path

physical_path_through_existing_ancestor() {
  local candidate=$1 probe suffix='' leaf physical
  probe=$candidate

  # The final path often does not exist on a first install. Resolve the deepest
  # directory that does exist with physical pwd semantics, then append only the
  # still-missing lexical suffix. This catches an alias in any ancestor without
  # requiring user destinations themselves to exist in advance.
  while [[ ! -d "$probe" ]]; do
    leaf=${probe##*/}
    suffix=/$leaf$suffix
    probe=${probe%/*}
    [[ -n "$probe" ]] || probe=/
  done
  physical=$(cd "$probe" 2>/dev/null && pwd -P) ||
    die "cannot resolve destination ancestor: $candidate"
  printf '%s%s\n' "${physical%/}" "$suffix"
}

physical_stable_root=$(physical_path_through_existing_ancestor "$stable_root")
physical_control_root=$(physical_path_through_existing_ancestor "$control_root")

reject_reserved_destination() {
  local candidate=$1 label=$2 candidate_physical reserved
  candidate_physical=$(physical_path_through_existing_ancestor "$candidate")
  for reserved in "$physical_stable_root" "$physical_control_root"; do
    case "$candidate_physical" in
      "$reserved" | "$reserved"/*)
        die "$label overlaps installer-owned state: $candidate"
        ;;
    esac
  done
}

# Publishing beneath the stable release link or private control tree can turn
# the link itself into a directory, alias a public command to the stable root,
# or expose installer metadata. Reject both destination directories and their
# concrete public paths before downloading, creating directories, or staging a
# release.
reject_reserved_destination "$bin_dir" 'command directory'
reject_reserved_destination "$command_link" 'public command'
if [[ -n "$release_manpage_path" ]]; then
  reject_reserved_destination "$man_dir" 'manual-page directory'
  reject_reserved_destination "$man_link" 'public manpage'
fi

if [[ -z "$archive" ]]; then
  command -v curl >/dev/null 2>&1 || die 'curl is required for online installation'
  [[ -z "$checksum" ]] || die '--checksum is valid only with --archive'

  # Bound connection setup, silent bodies, trickling transfers, and transient
  # failures for every GitHub request. Three calls at their worst-case retry
  # windows consume 546 seconds, below the online installer's ten-minute
  # network budget.
  curl_net_opts=(
    --connect-timeout 10
    --max-time 60
    --speed-limit 1024
    --speed-time 30
    --retry 2
    --retry-all-errors
    --retry-delay 1
  )

  if [[ -z "$requested_version" ]]; then
    latest_url=https://github.com/$release_repo/releases/latest
    resolved_url=$(curl "${curl_net_opts[@]}" -fsSL \
      --proto '=https' --proto-redir '=https' \
      -o /dev/null -w '%{url_effective}' "$latest_url") ||
      die "cannot resolve the latest $release_repo release"
    latest_prefix=https://github.com/$release_repo/releases/tag/
    case "$resolved_url" in
      "$latest_prefix"*) requested_version=${resolved_url#"$latest_prefix"} ;;
      *) die "latest-release redirect left the expected GitHub repository: $resolved_url" ;;
    esac
  fi
  [[ "$requested_version" =~ ^[0-9]{8}-[0-9]{6}-[0-9a-f]{8}$ ]] ||
    die "release version must look like YYYYMMDD-HHMMSS-<8hex>: $requested_version"

  scratch=$(mktemp -d "${TMPDIR:-/tmp}/$release_slug-install.XXXXXX") ||
    die 'cannot create private temporary directory'
  chmod 0700 "$scratch"
  archive_name=$release_asset_name-$requested_version-$release_platform.tar.gz
  archive=$scratch/$archive_name
  archive_is_private=1
  checksum=$archive.sha256
  download_base=https://github.com/$release_repo/releases/download/$requested_version
  curl "${curl_net_opts[@]}" -fsSL --proto '=https' --proto-redir '=https' \
    "$download_base/$archive_name.sha256" -o "$checksum" ||
    die "cannot download checksum for $archive_name"
  curl "${curl_net_opts[@]}" -fsSL --proto '=https' --proto-redir '=https' \
    "$download_base/$archive_name" -o "$archive" ||
    die "cannot download $archive_name"
fi
[[ -f "$archive" && ! -L "$archive" ]] ||
  die "archive must be a regular non-symlink file: $archive"
archive_dir=$(cd "$(dirname "$archive")" && pwd)
archive=$archive_dir/$(basename "$archive")

archive_name=$(basename "$archive")
archive_suffix=-$release_platform.tar.gz
case "$archive_name" in
  "$release_asset_name-"*"$archive_suffix") ;;
  *)
    die "archive name does not match $release_asset_name and platform $release_platform: $archive_name"
    ;;
esac
release_version=${archive_name#"$release_asset_name-"}
release_version=${release_version%"$archive_suffix"}
[[ "$release_version" =~ ^[0-9]{8}-[0-9]{6}-[0-9a-f]{8}$ ]] ||
  die "archive version must look like YYYYMMDD-HHMMSS-<8hex>: $release_version"
if [[ -n "$requested_version" && "$requested_version" != "$release_version" ]]; then
  die "archive version $release_version does not match requested version $requested_version"
fi

if [[ -z "$checksum" ]]; then
  checksum=$archive.sha256
fi
[[ -f "$checksum" && ! -L "$checksum" ]] ||
  die "checksum must be a regular non-symlink file: $checksum"

line_count=$(wc -l <"$checksum" | tr -d ' ')
[[ "$line_count" == 1 ]] ||
  die "checksum must contain exactly one record: $checksum"
IFS=' ' read -r expected_sha expected_name extra <"$checksum" ||
  die "cannot read checksum: $checksum"
[[ -z ${extra:-} && "$expected_sha" =~ ^[0-9a-f]{64}$ ]] ||
  die "checksum record is malformed: $checksum"
[[ "$expected_name" == "$archive_name" ]] ||
  die "checksum names $expected_name, expected $archive_name"

if [[ -z "$scratch" ]]; then
  scratch=$(mktemp -d "${TMPDIR:-/tmp}/$release_slug-install.XXXXXX") ||
    die 'cannot create private temporary directory'
  chmod 0700 "$scratch"
fi
if [[ "$archive_is_private" -eq 0 ]]; then
  archive_source=$archive
  archive=$scratch/archive.snapshot
  # A caller-provided path may live in a shared or otherwise mutable directory.
  # Snapshot it before hashing, listing, or extracting, and ask cp not to follow
  # a symlink if the source is swapped between our lstat-style check and copy.
  # The post-copy check then rejects a copied symlink. Every subsequent archive
  # operation uses this one private inode, closing the verify/use pathname race.
  cp -P "$archive_source" "$archive" ||
    die "cannot snapshot release archive: $archive_source"
  [[ -f "$archive" && ! -L "$archive" ]] ||
    die "archive changed while creating a private snapshot: $archive_source"
fi

actual_sha=$(sha256_file "$archive")
[[ "$actual_sha" == "$expected_sha" ]] ||
  die "checksum mismatch for $archive_name"

archive_list=$scratch/archive.list
archive_normalized=$scratch/archive.normalized
archive_verbose=$scratch/archive.verbose
extract_root=$scratch/root
mkdir "$extract_root"
: >"$archive_normalized"

tar -tzf "$archive" >"$archive_list" || die 'cannot list release archive'
[[ -s "$archive_list" ]] || die 'release archive is empty'
while IFS= read -r entry || [[ -n "$entry" ]]; do
  case "$entry" in
    . | ./) continue ;;
    ./*) relative=${entry#./} ;;
    *) relative=$entry ;;
  esac
  relative=${relative%/}
  case "$relative" in
    '' | .. | /* | *[!A-Za-z0-9._/+@=-]* | *//* | ../* | */../* | */.. | ./* | */./* | */.)
      die "unsafe archive path: $entry"
      ;;
  esac
  printf '%s\n' "$relative" >>"$archive_normalized"
done <"$archive_list"
duplicate=$(sort "$archive_normalized" | uniq -d | sed -n '1p')
[[ -z "$duplicate" ]] || die "duplicate archive path: $duplicate"

tar -tvzf "$archive" >"$archive_verbose" || die 'cannot inspect release archive'
while IFS= read -r verbose || [[ -n "$verbose" ]]; do
  type=${verbose:0:1}
  case "$type" in
    - | d) ;;
    *) die "release archive contains a non-file entry: $verbose" ;;
  esac
done <"$archive_verbose"

tar -xzf "$archive" -C "$extract_root" || die 'cannot extract release archive'

metadata=$extract_root/.$release_slug-install.json
binary=$extract_root/$release_binary_dest
[[ -f "$metadata" && ! -L "$metadata" ]] ||
  die "release metadata is missing: .$release_slug-install.json"
[[ -f "$binary" && ! -L "$binary" && -x "$binary" ]] ||
  die "release binary is missing or not executable: $release_binary_dest"
if [[ -n "$release_manpage_path" ]]; then
  [[ -f "$extract_root/$release_manpage_path" &&
    ! -L "$extract_root/$release_manpage_path" ]] ||
    die "declared manpage is missing: $release_manpage_path"
fi

metadata_string() {
  metadata_file=$1
  key=$2
  sed -n 's/^[[:space:]]*"'"$key"'"[[:space:]]*:[[:space:]]*"\([^"]*\)"[[:space:]]*,\{0,1\}[[:space:]]*$/\1/p' \
    "$metadata_file"
}

metadata_number() {
  metadata_file=$1
  key=$2
  sed -n 's/^[[:space:]]*"'"$key"'"[[:space:]]*:[[:space:]]*\([0-9][0-9]*\)[[:space:]]*,\{0,1\}[[:space:]]*$/\1/p' \
    "$metadata_file"
}

validate_metadata_identity() {
  candidate=$1
  metadata_schema=$(metadata_number "$candidate" schema)
  metadata_repo=$(metadata_string "$candidate" repo)
  metadata_platform=$(metadata_string "$candidate" artifact_platform)
  metadata_version=$(metadata_string "$candidate" version)
  metadata_tag=$(metadata_string "$candidate" tag)
  metadata_commit=$(metadata_string "$candidate" commit)
  metadata_method=$(metadata_string "$candidate" method)
  [[ "$metadata_schema" == 1 ]] ||
    die "release metadata schema is not supported: $metadata_schema"
  [[ "$metadata_repo" == "$release_repo" ]] ||
    die "release metadata repository mismatch: $metadata_repo"
  [[ "$metadata_platform" == "$release_platform" ]] ||
    die "release metadata platform mismatch: $metadata_platform"
  [[ "$metadata_version" == "$release_version" &&
    "$metadata_tag" == "$release_version" ]] ||
    die 'release metadata version does not match the archive name'
  [[ "$metadata_method" == release ]] ||
    die "release metadata method is not release: $metadata_method"
  [[ "$metadata_commit" =~ ^[0-9a-f]{8,}$ &&
    "${metadata_commit:0:8}" == "${release_version##*-}" ]] ||
    die 'release metadata commit does not match the release version'
}

validate_metadata_identity "$metadata"

owner_file=$control_root/owner
current_link=$control_root/current
releases_root=$control_root/releases
release_dir=$releases_root/$release_version-$release_platform

check_parent() {
  parent=$1
  if [[ -e "$parent" || -L "$parent" ]]; then
    [[ -d "$parent" && ! -L "$parent" ]] ||
      die "destination parent must be a regular directory: $parent"
  fi
}

check_link() {
  path=$1
  target=$2
  label=$3
  if [[ -e "$path" || -L "$path" ]]; then
    [[ -L "$path" && $(readlink "$path") == "$target" ]] ||
      die "$label path is already user-owned: $path"
  fi
}

check_parent "$data_home"
check_parent "$cgraf_root"
check_parent "$bin_dir"
if [[ -n "$release_manpage_path" ]]; then
  check_parent "$man_dir"
fi
if [[ -e "$control_root" || -L "$control_root" ]]; then
  [[ -d "$control_root" && ! -L "$control_root" ]] ||
    die "standalone control path is already user-owned: $control_root"
  [[ -f "$owner_file" && ! -L "$owner_file" &&
    $(cat "$owner_file") == "$owner_marker" ]] ||
    die "standalone control path lacks its ownership marker: $control_root"
fi
check_parent "$releases_root"
check_link "$stable_root" "$stable_target" 'stable release root'
check_link "$command_link" "$command_target" 'public command'
if [[ -n "$release_manpage_path" ]]; then
  check_link "$man_link" "$man_target" 'public manpage'
fi
if [[ -e "$current_link" || -L "$current_link" ]]; then
  [[ -L "$current_link" && $(readlink "$current_link") == releases/* ]] ||
    die "active release link is not installer-owned: $current_link"
fi

mkdir -p "$cgraf_root" "$bin_dir"
if [[ -n "$release_manpage_path" ]]; then
  mkdir -p "$man_dir"
fi
if [[ ! -e "$control_root" && ! -L "$control_root" ]]; then
  mkdir -m 0700 "$control_root"
  printf '%s\n' "$owner_marker" >"$owner_file"
  chmod 0600 "$owner_file"
fi
mkdir -p "$releases_root"
chmod 0700 "$control_root" "$releases_root"

lock_dir=$control_root/lock
mkdir "$lock_dir" 2>/dev/null ||
  die "another installer is active (or left a stale lock): $lock_dir"
lock_held=1

if [[ -e "$release_dir" || -L "$release_dir" ]]; then
  [[ -d "$release_dir" && ! -L "$release_dir" ]] ||
    die "release path is not a regular directory: $release_dir"
  existing_metadata=$release_dir/.$release_slug-install.json
  existing_binary=$release_dir/$release_binary_dest
  [[ -f "$existing_metadata" && ! -L "$existing_metadata" &&
    -f "$existing_binary" && ! -L "$existing_binary" && -x "$existing_binary" ]] ||
    die "existing release tree is incomplete: $release_dir"
  if [[ -n "$release_manpage_path" ]]; then
    [[ -f "$release_dir/$release_manpage_path" &&
      ! -L "$release_dir/$release_manpage_path" ]] ||
      die "existing release tree is missing its manpage: $release_dir"
  fi
  # A path below our marked control root is still mutable by the user. Recheck
  # both identity and every archived byte before a same-version rerun can make
  # it current. The freshly extracted, checksum-verified tree is the reference;
  # a directory name alone is not an integrity receipt.
  validate_metadata_identity "$existing_metadata"
  archive_sorted=$scratch/archive.sorted
  existing_normalized=$scratch/existing.normalized
  existing_sorted=$scratch/existing.sorted
  sort "$archive_normalized" >"$archive_sorted"
  : >"$existing_normalized"
  while IFS= read -r entry || [[ -n "$entry" ]]; do
    relative=${entry#./}
    printf '%s\n' "$relative" >>"$existing_normalized"
  done < <(cd "$release_dir" && find . -mindepth 1 -print)
  sort "$existing_normalized" >"$existing_sorted"
  archive_digest=$(sha256_file "$archive_sorted")
  existing_digest=$(sha256_file "$existing_sorted")
  [[ "$archive_digest" == "$existing_digest" ]] ||
    die "existing release tree has missing or extra entries: $release_dir"
  while IFS= read -r entry || [[ -n "$entry" ]]; do
    case "$entry" in
      . | ./) continue ;;
      ./*) relative=${entry#./} ;;
      *) relative=$entry ;;
    esac
    relative=${relative%/}
    extracted_entry=$extract_root/$relative
    existing_entry=$release_dir/$relative
    if [[ -d "$extracted_entry" && ! -L "$extracted_entry" ]]; then
      [[ -d "$existing_entry" && ! -L "$existing_entry" ]] ||
        die "existing release tree differs at $relative"
    else
      [[ -f "$existing_entry" && ! -L "$existing_entry" ]] ||
        die "existing release tree differs at $relative"
      extracted_digest=$(sha256_file "$extracted_entry")
      existing_digest=$(sha256_file "$existing_entry")
      [[ "$extracted_digest" == "$existing_digest" ]] ||
        die "existing release tree differs at $relative"
      if [[ -x "$extracted_entry" && ! -x "$existing_entry" ]] ||
        [[ ! -x "$extracted_entry" && -x "$existing_entry" ]]; then
        die "existing release executable mode differs at $relative"
      fi
    fi
  done <"$archive_list"
else
  incoming=$releases_root/.incoming.$$
  [[ ! -e "$incoming" && ! -L "$incoming" ]] ||
    die "temporary release path already exists: $incoming"
  mkdir -m 0700 "$incoming"
  cp -R "$extract_root/." "$incoming/"
  mv "$incoming" "$release_dir"
  incoming=
fi

next_current=$control_root/.current.$$
[[ ! -e "$next_current" && ! -L "$next_current" ]] ||
  die "temporary activation path already exists: $next_current"
ln -s "releases/$release_version-$release_platform" "$next_current"
# GNU/BusyBox and BSD spell "replace a symlink-to-directory without following
# it" differently. Both operations are same-directory renames, so readers see
# either the complete old target or the complete new target during an update.
if mv -fT "$next_current" "$current_link" 2>/dev/null; then
  :
else
  mv -fh "$next_current" "$current_link"
fi
next_current=

# Publish the internal activation before creating any first-install public
# links. If the no-follow rename fails, users retain no dangling stable root,
# command, or manpage; the fully staged release remains safe for a retry.
if [[ ! -e "$stable_root" && ! -L "$stable_root" ]]; then
  published_stable=1
  ln -s "$stable_target" "$stable_root"
fi
if [[ ! -e "$command_link" && ! -L "$command_link" ]]; then
  published_command=1
  ln -s "$command_target" "$command_link"
fi
if [[ -n "$release_manpage_path" && ! -e "$man_link" && ! -L "$man_link" ]]; then
  published_man=1
  ln -s "$man_target" "$man_link"
fi

# Publication completed as one logical operation. From this point onward the
# EXIT trap must leave the stable, command, and manpage links active.
published_stable=0
published_command=0
published_man=0

printf 'Installed %s %s for %s\n' \
  "$release_slug" "$release_version" "$release_platform"
