//! Stateful v2 relay server and navigation commit transaction.
//!
//! A navigation request cannot mutate an inner tmux immediately: terminal
//! output generated by an outer SSH/tmux chain may still be in flight. The
//! relay first prepares one directive per tmux hop, emits a read-only terminal
//! query at the outer edge, and commits inward only when the reply traverses
//! the exact clients that were validated during preparation.

use std::fs::{self, File, OpenOptions};
use std::io::{self, BufRead, BufReader, Read, Write};
use std::os::fd::{AsRawFd, OwnedFd, RawFd};
use std::os::unix::fs::{FileTypeExt, MetadataExt, OpenOptionsExt, PermissionsExt};
use std::os::unix::net::{UnixListener, UnixStream};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicBool, AtomicI32, AtomicU64, Ordering};
use std::sync::mpsc::SyncSender;
use std::sync::{Arc, Condvar, Mutex};
use std::thread;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use serde_json::{Value, json};

use super::client::send;
use super::store::{Directive, DirectiveAction, Store};
use crate::navigation::{Action, Backend, Client, Direction, Outcome, Scope, SystemBackend};
use crate::process;

const MAX_MESSAGE_BYTES: u64 = 513;
// A client can be descheduled after connect(2) but before its first write,
// especially while a multi-hop navigation burst is starting helper processes
// on a loaded host. Keep admission bounded, but allow ordinary scheduler
// latency rather than converting it into a broken pipe on the user's gesture.
// The private socket and handler cap below bound deliberate idle connections.
const REQUEST_TIMEOUT: Duration = Duration::from_secs(2);
const RELAY_TIMEOUT: Duration = Duration::from_secs(8);
const COMMIT_QUERY: &[u8] = b"\x1b[?2004$p";
const COMMIT_KEY: &[u8] = b"\x1b[777009u";
const MAX_CONNECTION_HANDLERS: usize = 64;

static STOPPING: AtomicBool = AtomicBool::new(false);
static WAKE_WRITE: AtomicI32 = AtomicI32::new(-1);
static LAST_SIGNAL: AtomicI32 = AtomicI32::new(0);

/// Stable identity of the terminal that owns a relay outside tmux.
#[derive(Clone)]
pub struct DirectTerminal {
    /// PID whose controlling terminal must still match at dispatch time.
    pub pid: u32,
    /// Character device used for the terminal commit barrier.
    pub tty: String,
    /// Terminal type exposed to navigation backends.
    pub termtype: String,
    /// Writable descriptor captured before SSH can replace the foreground job.
    output: Arc<File>,
}

impl DirectTerminal {
    /// Build an identity captured before the SSH supervisor starts threads.
    #[must_use]
    pub fn captured(pid: u32, tty: String, termtype: String, output: File) -> Self {
        Self {
            pid,
            tty,
            termtype,
            output: Arc::new(output),
        }
    }

    fn emit_commit(&self) -> bool {
        // Android may allow an inherited terminal descriptor while refusing a
        // later pathname reopen of the same /dev/pts node. Retaining this
        // descriptor also removes a time-of-check/time-of-use window between
        // terminal identity capture and the commit barrier.
        let mut output = self.output.as_ref();
        output.write_all(COMMIT_QUERY).is_ok()
    }
}

/// Serve requests on one owner-protected Unix socket.
pub fn serve(
    path: &Path,
    owner_fd: Option<RawFd>,
    direct_terminal: Option<DirectTerminal>,
) -> io::Result<()> {
    serve_inner(path, owner_fd, direct_terminal, None)
}

/// Serve after notifying the in-process SSH supervisor that setup is complete.
pub(crate) fn serve_ready(
    path: &Path,
    owner_fd: Option<RawFd>,
    direct_terminal: Option<DirectTerminal>,
    ready: SyncSender<()>,
) -> io::Result<()> {
    serve_inner(path, owner_fd, direct_terminal, Some(ready))
}

fn serve_inner(
    path: &Path,
    owner_fd: Option<RawFd>,
    direct_terminal: Option<DirectTerminal>,
    ready: Option<SyncSender<()>>,
) -> io::Result<()> {
    STOPPING.store(false, Ordering::SeqCst);
    LAST_SIGNAL.store(0, Ordering::SeqCst);
    prepare_socket_path(path)?;
    let old_umask = unsafe { libc::umask(0o177) };
    let listener = UnixListener::bind(path);
    unsafe { libc::umask(old_umask) };
    let listener = listener?;
    // Binding creates the filesystem entry before any of the remaining setup
    // can fail. Own it immediately so chmod, nonblocking, pipe, and signal
    // setup errors cannot strand a path that later looks like a live relay.
    let mut socket_path = SocketPathGuard::new(path);
    fs::set_permissions(path, fs::Permissions::from_mode(0o600))?;
    listener.set_nonblocking(true)?;

    let (wake_read, wake_write) = process::pipe(true)?;
    WAKE_WRITE.store(wake_write.as_raw_fd(), Ordering::SeqCst);
    install_signal_handlers()?;
    let ordering = Arc::new(OrderGate::default());
    if let Some(ready) = ready {
        // Binding alone is not readiness: every fallible permission, pipe,
        // and signal setup step above must complete before SSH advertises this
        // socket as a reverse forward.
        let _ = ready.send(());
    }

    // `poll` has no periodic wakeup: the process sleeps until a connection,
    // owner death, or catchable signal. This keeps the connection-owned relay
    // effectively free while idle and lets the kernel close it immediately if
    // the supervisor is killed.
    let result = poll_loop(&listener, owner_fd, &wake_read, ordering, direct_terminal);
    WAKE_WRITE.store(-1, Ordering::SeqCst);
    drop(listener);
    if let Err(error) = socket_path.remove()
        && result.is_ok()
    {
        return Err(error);
    }
    result
}

struct SocketPathGuard {
    path: PathBuf,
    armed: bool,
}

impl SocketPathGuard {
    fn new(path: &Path) -> Self {
        Self {
            path: path.to_owned(),
            armed: true,
        }
    }

    fn remove(&mut self) -> io::Result<()> {
        match fs::remove_file(&self.path) {
            Ok(()) => {
                self.armed = false;
                Ok(())
            }
            Err(error) if error.kind() == io::ErrorKind::NotFound => {
                self.armed = false;
                Ok(())
            }
            Err(error) => Err(error),
        }
    }
}

impl Drop for SocketPathGuard {
    fn drop(&mut self) {
        if self.armed {
            let _ = fs::remove_file(&self.path);
        }
    }
}

/// Return the catchable signal that requested relay shutdown, if any.
#[must_use]
pub fn shutdown_signal() -> Option<i32> {
    let signal = LAST_SIGNAL.load(Ordering::SeqCst);
    (signal > 0).then_some(signal)
}

/// Handle one validated protocol object without socket framing.
#[must_use]
pub fn dispatch(request: &Value) -> Value {
    dispatch_with_terminal(request, None)
}

fn dispatch_with_terminal(request: &Value, direct_terminal: Option<&DirectTerminal>) -> Value {
    if request.get("v").and_then(Value::as_u64) != Some(2) {
        return reply("error");
    }
    match request.get("op").and_then(Value::as_str) {
        Some("navigate") => handle_navigate(request, direct_terminal),
        Some("prepare-path") => handle_prepare(request),
        Some("abort-path") => handle_abort(request),
        Some("commit-path") => handle_commit(request, direct_terminal),
        Some("focus") => crate::focus::handle_relay(request),
        _ => reply("error"),
    }
}

/// Send a navigation request to the parent advertised by a live client.
#[must_use]
pub fn send_navigation(
    action: Action,
    direction: Direction,
    client_pid: Option<u32>,
    client_tty: Option<&str>,
    parent_override: Option<&str>,
) -> i32 {
    let mut parent = client_pid
        .and_then(|pid| process::environment(pid, "TERMNAV_PARENT_RELAY"))
        .filter(|value| !value.is_empty());
    if parent.is_none() {
        parent = parent_override
            .map(str::to_owned)
            .or_else(|| std::env::var("TERMNAV_PARENT_RELAY").ok())
            .filter(|value| !value.is_empty());
    }
    if let (Some(pid), Some(tty)) = (client_pid, client_tty)
        && !process::tty_matches(pid, tty)
    {
        return if parent.is_some() { 1 } else { 3 };
    }
    let Some(parent) = parent else {
        return 3;
    };
    let request = json!({
        "v": 2,
        "op": "navigate",
        // Protocol v2 uses compact scope names. Keep that vocabulary isolated
        // at this boundary so mixed-version SSH paths interoperate without
        // exposing old names through the unified public command interface.
        "scope": wire_scope(action),
        "direction": direction.as_str(),
        "nonce": super::client::new_nonce(),
    });
    match send(Path::new(&parent), &request, RELAY_TIMEOUT)
        .ok()
        .and_then(|response| {
            response
                .get("result")
                .and_then(Value::as_str)
                .map(str::to_owned)
        })
        .as_deref()
    {
        Some("armed") => 0,
        Some("declined") => 3,
        _ => 1,
    }
}

/// Consume one terminal commit response for an exact tmux client.
#[allow(clippy::too_many_arguments)]
pub fn commit(
    tmux_socket: &str,
    client_tty: &str,
    client_pid: u32,
    client_created: u64,
    passthrough_state: Option<u8>,
    passthrough_pane: Option<&str>,
) -> i32 {
    let unmatched = || {
        if let (Some(state), Some(pane)) = (passthrough_state, passthrough_pane)
            && state <= 4
            && valid_pane(pane)
        {
            let response = format!("\x1b[?2004;{state}$y");
            let bytes = response
                .as_bytes()
                .iter()
                .map(|byte| format!("{byte:02x}"))
                .collect::<Vec<_>>();
            let mut arguments = vec![
                "-S".to_owned(),
                tmux_socket.to_owned(),
                "send-keys".to_owned(),
                "-t".to_owned(),
                pane.to_owned(),
                "-H".to_owned(),
            ];
            arguments.extend(bytes);
            let _ = run_tmux(&arguments);
        }
        0
    };

    if client_pid == 0 || !character_device(client_tty) {
        return unmatched();
    }
    let listed = run_tmux(&[
        "-S".to_owned(),
        tmux_socket.to_owned(),
        "list-clients".to_owned(),
        "-F".to_owned(),
        "#{client_tty} #{client_pid} #{client_created}".to_owned(),
    ]);
    let Some(listed) = listed.filter(|output| output.status.success()) else {
        return unmatched();
    };
    let expected = format!("{client_tty} {client_pid} {client_created}");
    if !String::from_utf8_lossy(&listed.stdout)
        .lines()
        .any(|line| line == expected)
    {
        return unmatched();
    }

    let Ok(store) = Store::open(tmux_socket) else {
        return unmatched();
    };
    let Ok(Some(directive)) = store.claim(client_tty, client_pid, client_created) else {
        return unmatched();
    };
    if directive.tmux_socket != tmux_socket
        || directive.local_client_tty != client_tty
        || directive.local_client_pid != client_pid
        || !validate_directive_client(&directive)
    {
        let _ = store.record_result(&directive.nonce, false);
        return 0;
    }

    let handled = match directive.action {
        DirectiveAction::Forward => directive.forward_pane.as_deref().is_some_and(|pane| {
            let mut arguments = vec![
                "-S".to_owned(),
                tmux_socket.to_owned(),
                "send-keys".to_owned(),
                "-t".to_owned(),
                pane.to_owned(),
                "-H".to_owned(),
            ];
            arguments.extend(COMMIT_KEY.iter().map(|byte| format!("{byte:02x}")));
            run_tmux(&arguments).is_some_and(|output| output.status.success())
        }),
        DirectiveAction::Execute => execute_directive(&directive),
    };
    let _ = store.record_result(&directive.nonce, handled);
    0
}

fn handle_navigate(request: &Value, direct_terminal: Option<&DirectTerminal>) -> Value {
    let Some(nonce) = request
        .get("nonce")
        .and_then(Value::as_str)
        .filter(|value| valid_nonce(value))
    else {
        return reply("error");
    };
    let Some(scope_name) = request.get("scope").and_then(Value::as_str) else {
        return reply("error");
    };
    let Some(direction_name) = request.get("direction").and_then(Value::as_str) else {
        return reply("error");
    };
    let Some((action, direction)) = wire_action(scope_name, direction_name) else {
        return reply("error");
    };

    let mut backend = SystemBackend::from_current_environment();
    let info = local_scope(&mut backend);
    if has_incomplete_tmux(&info) {
        return reply("error");
    }
    if let Some(info) = info.as_ref()
        && backend.can_execute(&info.scope, action, direction)
    {
        let mut directive = execute_record(info, nonce, scope_name, direction_name);
        let Ok(store) = Store::open(&info.scope.socket) else {
            return reply("error");
        };
        if store.arm(&mut directive).is_err() {
            return reply("error");
        }
        let parent = parent_relay(Some(info));
        if !parent.is_empty() {
            let prepared = send(
                Path::new(&parent),
                &json!({"v": 2, "op": "prepare-path", "nonce": nonce}),
                RELAY_TIMEOUT,
            )
            .ok();
            if prepared.as_ref().and_then(result) != Some("prepared") {
                abort_parent(&parent, nonce);
                let _ = store.discard(nonce);
                return reply("error");
            }
        }
        if !validate_directive_client(&directive) || !store.mark_committed(nonce).unwrap_or(false) {
            abort_parent(&parent, nonce);
            let _ = store.discard(nonce);
            return reply("error");
        }
        if parent.is_empty() {
            if !emit_commit(&directive.local_client_tty) {
                let _ = store.discard(nonce);
                return reply("error");
            }
        } else {
            // Once commit begins, an RPC reply is advisory: an outer hop may
            // already have emitted the terminal query. Only the durable receipt
            // can prove whether retrying would duplicate the gesture.
            let _ = send(
                Path::new(&parent),
                &json!({"v": 2, "op": "commit-path", "nonce": nonce}),
                RELAY_TIMEOUT,
            );
        }
        return if store.wait_for_consumption(nonce).unwrap_or(false) {
            reply("armed")
        } else {
            reply("error")
        };
    }

    let parent = parent_relay(info.as_ref());
    if !parent.is_empty() {
        return send(Path::new(&parent), request, RELAY_TIMEOUT)
            .ok()
            .filter(valid_navigation_reply)
            .unwrap_or_else(|| reply("error"));
    }
    reply(dispatch_terminal(
        &mut backend,
        info.as_ref(),
        direct_terminal,
        action,
        direction,
    ))
}

fn handle_prepare(request: &Value) -> Value {
    let Some(nonce) = request
        .get("nonce")
        .and_then(Value::as_str)
        .filter(|value| valid_nonce(value))
    else {
        return reply("error");
    };
    let mut backend = SystemBackend::from_current_environment();
    let info = local_scope(&mut backend);
    if has_incomplete_tmux(&info) {
        return reply("error");
    }
    let parent = parent_relay(info.as_ref());
    let Some(info) = info else {
        return if parent.is_empty() {
            reply("prepared")
        } else {
            send(Path::new(&parent), request, RELAY_TIMEOUT).unwrap_or_else(|_| reply("error"))
        };
    };
    let mut directive = forward_record(&info, nonce);
    let Ok(store) = Store::open(&info.scope.socket) else {
        return reply("error");
    };
    if store.arm(&mut directive).is_err() {
        return reply("error");
    }
    if parent.is_empty() {
        return reply("prepared");
    }
    let response = send(Path::new(&parent), request, RELAY_TIMEOUT).ok();
    if response.as_ref().and_then(result) == Some("prepared") {
        return response.unwrap_or_else(|| reply("error"));
    }
    abort_parent(&parent, nonce);
    let _ = store.discard(nonce);
    reply("error")
}

fn handle_abort(request: &Value) -> Value {
    let Some(nonce) = request
        .get("nonce")
        .and_then(Value::as_str)
        .filter(|value| valid_nonce(value))
    else {
        return reply("error");
    };
    let mut backend = SystemBackend::from_current_environment();
    let current = backend.current_scope();
    if let Some(current) = current {
        let Ok(store) = Store::open(&current.socket) else {
            return reply("error");
        };
        let parent = store
            .read(nonce)
            .ok()
            .flatten()
            .map(|directive| {
                let parent =
                    process::environment(directive.local_client_pid, "TERMNAV_PARENT_RELAY")
                        .unwrap_or_default();
                let _ = store.discard(nonce);
                parent
            })
            .unwrap_or_else(|| parent_relay(local_scope(&mut backend).as_ref()));
        abort_parent(&parent, nonce);
        return reply("aborted");
    }
    if std::env::var_os("TMUX").is_some() && std::env::var_os("TMUX_PANE").is_some() {
        return reply("error");
    }
    abort_parent(&parent_relay(None), nonce);
    reply("aborted")
}

fn handle_commit(request: &Value, direct_terminal: Option<&DirectTerminal>) -> Value {
    let Some(nonce) = request
        .get("nonce")
        .and_then(Value::as_str)
        .filter(|value| valid_nonce(value))
    else {
        return reply("error");
    };
    let mut backend = SystemBackend::from_current_environment();
    if let Some(current) = backend.current_scope() {
        let Ok(store) = Store::open(&current.socket) else {
            return reply("error");
        };
        let Ok(Some(directive)) = store.read(nonce) else {
            return reply("error");
        };
        if directive.action != DirectiveAction::Forward
            || !validate_directive_client(&directive)
            || !store.mark_committed(nonce).unwrap_or(false)
        {
            let _ = store.discard(nonce);
            return reply("error");
        }
        let parent = process::environment(directive.local_client_pid, "TERMNAV_PARENT_RELAY")
            .unwrap_or_default();
        if parent.is_empty() {
            if !emit_commit(&directive.local_client_tty) {
                let _ = store.discard(nonce);
                return reply("error");
            }
        } else {
            let _ = send(
                Path::new(&parent),
                &json!({"v": 2, "op": "commit-path", "nonce": nonce}),
                RELAY_TIMEOUT,
            );
        }
        return if store.wait_for_consumption(nonce).unwrap_or(false) {
            reply("emitted")
        } else {
            reply("error")
        };
    }
    if std::env::var_os("TMUX").is_some() && std::env::var_os("TMUX_PANE").is_some() {
        return reply("error");
    }
    let parent = parent_relay(None);
    if !parent.is_empty() {
        return send(
            Path::new(&parent),
            &json!({"v": 2, "op": "commit-path", "nonce": nonce}),
            RELAY_TIMEOUT,
        )
        .ok()
        .filter(valid_navigation_reply)
        .unwrap_or_else(|| reply("error"));
    }
    let Some(direct_terminal) = direct_terminal else {
        return reply("error");
    };
    if direct_terminal.emit_commit() {
        reply("emitted")
    } else {
        reply("error")
    }
}

struct LocalScope {
    scope: Scope,
    client: Client,
    started_at: u64,
}

fn local_scope(backend: &mut SystemBackend) -> Option<LocalScope> {
    let current = backend.current_scope()?;
    let started_at = now_seconds();
    let client = backend.resolve_client(&current, started_at)?;
    Some(LocalScope {
        scope: Scope {
            socket: current.socket,
            pane: current.pane,
            session: Some(client.session.clone()),
        },
        client,
        started_at,
    })
}

fn has_incomplete_tmux(info: &Option<LocalScope>) -> bool {
    info.is_none() && std::env::var_os("TMUX").is_some() && std::env::var_os("TMUX_PANE").is_some()
}

fn parent_relay(info: Option<&LocalScope>) -> String {
    info.and_then(|scope| process::environment(scope.client.pid, "TERMNAV_PARENT_RELAY"))
        .or_else(|| std::env::var("TERMNAV_PARENT_RELAY").ok())
        .unwrap_or_default()
}

fn execute_record(info: &LocalScope, nonce: &str, scope: &str, direction: &str) -> Directive {
    Directive {
        v: 2,
        nonce: nonce.to_owned(),
        seq: 0,
        action: DirectiveAction::Execute,
        ready: false,
        claimed: false,
        prepared_at: 0.0,
        owner_pid: 0,
        tmux_socket: info.scope.socket.clone(),
        session: info.client.session.clone(),
        local_client_tty: info.client.tty.clone(),
        local_client_pid: info.client.pid,
        local_client_created: info.client.created,
        started_at: info.started_at,
        expected_pane: Some(info.scope.pane.clone()),
        target_pane: Some(info.scope.target()),
        scope: Some(scope.to_owned()),
        direction: Some(direction.to_owned()),
        forward_pane: None,
    }
}

fn forward_record(info: &LocalScope, nonce: &str) -> Directive {
    Directive {
        v: 2,
        nonce: nonce.to_owned(),
        seq: 0,
        action: DirectiveAction::Forward,
        ready: false,
        claimed: false,
        prepared_at: 0.0,
        owner_pid: 0,
        tmux_socket: info.scope.socket.clone(),
        session: info.client.session.clone(),
        local_client_tty: info.client.tty.clone(),
        local_client_pid: info.client.pid,
        local_client_created: info.client.created,
        started_at: info.started_at,
        expected_pane: None,
        target_pane: None,
        scope: None,
        direction: None,
        forward_pane: Some(info.scope.pane.clone()),
    }
}

fn validate_directive_client(directive: &Directive) -> bool {
    let pane = directive
        .expected_pane
        .as_ref()
        .or(directive.forward_pane.as_ref())
        .cloned()
        .unwrap_or_default();
    let client = Client {
        activity: 0,
        pid: directive.local_client_pid,
        tty: directive.local_client_tty.clone(),
        termtype: String::new(),
        session: directive.session.clone(),
        pane,
        focused: false,
        control: false,
        socket: directive.tmux_socket.clone(),
        exact: false,
        created: directive.local_client_created,
    };
    SystemBackend::from_current_environment().validate_client(&client, directive.started_at)
}

fn execute_directive(directive: &Directive) -> bool {
    let Some((action, direction)) = directive
        .scope
        .as_deref()
        .zip(directive.direction.as_deref())
        .and_then(|(scope, direction)| wire_action(scope, direction))
    else {
        return false;
    };
    let Some(pane) = directive.expected_pane.clone() else {
        return false;
    };
    let scope = Scope {
        socket: directive.tmux_socket.clone(),
        pane,
        session: Some(directive.session.clone()),
    };
    SystemBackend::from_current_environment().execute(&scope, action, direction) == Outcome::Handled
}

fn dispatch_terminal(
    backend: &mut SystemBackend,
    info: Option<&LocalScope>,
    direct_terminal: Option<&DirectTerminal>,
    action: Action,
    direction: Direction,
) -> &'static str {
    let direct = direct_terminal_client(direct_terminal);
    let client = info.map(|scope| &scope.client).or(direct.as_ref());
    if info.is_none() && client.is_none() {
        return "declined";
    }
    if let Some(client) = client
        && !backend.validate_client(client, now_seconds())
    {
        return "error";
    }
    match backend.terminal(client, action, direction) {
        Outcome::Handled => "armed",
        Outcome::Declined => "declined",
        Outcome::Error => "error",
    }
}

fn direct_terminal_client(direct_terminal: Option<&DirectTerminal>) -> Option<Client> {
    let direct_terminal = direct_terminal?;
    Some(Client {
        activity: 0,
        pid: direct_terminal.pid,
        tty: direct_terminal.tty.clone(),
        termtype: direct_terminal.termtype.clone(),
        session: String::new(),
        pane: String::new(),
        focused: false,
        control: false,
        socket: String::new(),
        exact: true,
        created: 0,
    })
}

fn emit_commit(tty: &str) -> bool {
    if tty.is_empty() {
        return false;
    }
    let Ok(mut descriptor) = OpenOptions::new()
        .append(true)
        .custom_flags(libc::O_NOCTTY)
        .open(tty)
    else {
        return false;
    };
    descriptor.write_all(COMMIT_QUERY).is_ok()
}

fn abort_parent(parent: &str, nonce: &str) {
    if parent.is_empty() {
        return;
    }
    let _ = send(
        Path::new(parent),
        &json!({"v": 2, "op": "abort-path", "nonce": nonce}),
        RELAY_TIMEOUT,
    );
}

fn wire_action(scope: &str, direction: &str) -> Option<(Action, Direction)> {
    let action = match scope {
        "pane" => Action::PaneSelect,
        "window" => Action::TabSelect,
        "move" => Action::TabMove,
        _ => return None,
    };
    Direction::parse(action, direction)
        .ok()
        .map(|direction| (action, direction))
}

fn wire_scope(action: Action) -> &'static str {
    match action {
        Action::PaneSelect => "pane",
        Action::TabSelect => "window",
        Action::TabMove => "move",
    }
}

fn valid_nonce(value: &str) -> bool {
    value.len() == 12 && value.bytes().all(|byte| byte.is_ascii_hexdigit())
}

fn valid_pane(value: &str) -> bool {
    value.strip_prefix('%').is_some_and(|digits| {
        !digits.is_empty() && digits.bytes().all(|byte| byte.is_ascii_digit())
    })
}

fn character_device(path: &str) -> bool {
    fs::metadata(path).is_ok_and(|metadata| metadata.file_type().is_char_device())
}

fn result(reply: &Value) -> Option<&str> {
    reply.get("result").and_then(Value::as_str)
}

fn reply(result: &str) -> Value {
    json!({"v": 2, "result": result})
}

fn valid_navigation_reply(value: &Value) -> bool {
    value.get("v").and_then(Value::as_u64) == Some(2)
        && matches!(
            result(value),
            Some("armed" | "declined" | "error" | "emitted")
        )
}

fn now_seconds() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

fn run_tmux(arguments: &[String]) -> Option<std::process::Output> {
    let mut command = Command::new("tmux");
    command.args(arguments).env_remove("TMUX");
    process::output_timeout(&mut command, Duration::from_secs(2)).ok()
}

fn prepare_socket_path(path: &Path) -> io::Result<()> {
    let Some(parent) = path.parent() else {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "relay socket has no parent",
        ));
    };
    // Socket creation must not turn an arbitrary symlink or another user's
    // directory into trusted transport state. Keep this check centralized
    // with every other Termnav runtime directory boundary.
    crate::runtime::ensure_private_directory(parent)?;
    match fs::symlink_metadata(path) {
        Ok(metadata) => {
            let uid = unsafe { libc::getuid() };
            if !metadata.file_type().is_socket() || metadata.uid() != uid {
                return Err(io::Error::new(
                    io::ErrorKind::PermissionDenied,
                    "refusing to replace unsafe relay socket path",
                ));
            }
            fs::remove_file(path)?;
        }
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => return Err(error),
    }
    Ok(())
}

fn poll_loop(
    listener: &UnixListener,
    owner_fd: Option<RawFd>,
    wake_read: &OwnedFd,
    ordering: Arc<OrderGate>,
    direct_terminal: Option<DirectTerminal>,
) -> io::Result<()> {
    let mut handlers = Vec::new();
    while !STOPPING.load(Ordering::SeqCst) {
        let mut descriptors = vec![libc::pollfd {
            fd: listener.as_raw_fd(),
            events: libc::POLLIN,
            revents: 0,
        }];
        let owner_index = owner_fd.map(|fd| {
            descriptors.push(libc::pollfd {
                fd,
                events: libc::POLLIN | libc::POLLHUP,
                revents: 0,
            });
            descriptors.len() - 1
        });
        let wake_index = descriptors.len();
        descriptors.push(libc::pollfd {
            fd: wake_read.as_raw_fd(),
            events: libc::POLLIN,
            revents: 0,
        });
        let ready = unsafe { libc::poll(descriptors.as_mut_ptr(), descriptors.len() as _, -1) };
        if ready < 0 {
            let error = io::Error::last_os_error();
            if error.kind() == io::ErrorKind::Interrupted {
                continue;
            }
            return Err(error);
        }
        if descriptors[wake_index].revents & libc::POLLIN != 0 {
            let mut byte = [0_u8; 64];
            let _ =
                unsafe { libc::read(wake_read.as_raw_fd(), byte.as_mut_ptr().cast(), byte.len()) };
        }
        if STOPPING.load(Ordering::SeqCst) {
            break;
        }
        if owner_index.is_some_and(|index| descriptors[index].revents != 0) {
            let mut byte = [0_u8; 1];
            let read =
                unsafe { libc::read(owner_fd.expect("index exists"), byte.as_mut_ptr().cast(), 1) };
            if read <= 0 {
                break;
            }
        }
        if descriptors[0].revents & libc::POLLIN == 0 {
            continue;
        }
        reap_finished(&mut handlers);
        match listener.accept() {
            Ok((stream, _)) => {
                reap_finished(&mut handlers);
                if handlers.len() >= MAX_CONNECTION_HANDLERS {
                    // The socket is private to the user, but a stuck or buggy
                    // client must not create unbounded thread stacks or turn
                    // shutdown into an N-times-timeout delay.
                    drop(stream);
                    continue;
                }
                let ordering = Arc::clone(&ordering);
                let direct_terminal = direct_terminal.clone();
                handlers.push(thread::spawn(move || {
                    handle_connection(stream, owner_fd, ordering, direct_terminal.as_ref())
                }));
            }
            Err(error) if error.kind() == io::ErrorKind::WouldBlock => {}
            Err(error) => return Err(error),
        }
    }
    ordering.stop();
    // No new requests are accepted after owner death, but an admitted request
    // owns transactional state that must reach its bounded success/abort path.
    // Draining only active handlers prevents dead-owner directives from
    // poisoning a still-live outer tmux client after the SSH wrapper exits.
    for handler in handlers {
        let _ = handler.join();
    }
    Ok(())
}

fn reap_finished(handlers: &mut Vec<thread::JoinHandle<()>>) {
    let mut index = 0;
    while index < handlers.len() {
        if handlers[index].is_finished() {
            let handler = handlers.swap_remove(index);
            let _ = handler.join();
        } else {
            index += 1;
        }
    }
}

fn handle_connection(
    mut stream: UnixStream,
    owner_fd: Option<RawFd>,
    ordering: Arc<OrderGate>,
    direct_terminal: Option<&DirectTerminal>,
) {
    // BSD-derived kernels may propagate O_NONBLOCK from the listener to an
    // accepted socket. Linux does not, which hid this portability bug until a
    // macOS client was deliberately descheduled between connect and write.
    // Normalize the per-request stream before applying bounded blocking I/O;
    // otherwise the first read can return WouldBlock and close a valid gesture.
    if stream.set_nonblocking(false).is_err()
        || stream.set_read_timeout(Some(REQUEST_TIMEOUT)).is_err()
        || stream.set_write_timeout(Some(RELAY_TIMEOUT)).is_err()
    {
        return;
    }
    let mut line = String::new();
    let mut reader = BufReader::new((&mut stream).take(MAX_MESSAGE_BYTES));
    if reader.read_line(&mut line).is_err() || line.len() > 512 || !line.ends_with('\n') {
        return;
    }
    let Ok(request) = serde_json::from_str::<Value>(&line) else {
        return;
    };
    if !request.is_object() {
        return;
    }

    let response = if request.get("op").and_then(Value::as_str) == Some("focus") {
        if ordering.stopped() {
            return;
        }
        dispatch_with_terminal(&request, direct_terminal)
    } else {
        let Some(ticket) = ordering.enter() else {
            return;
        };
        // The poll thread and the active handler race when the owner closes at
        // the exact instant a transaction finishes. Recheck the kernel-owned
        // lifetime signal after acquiring the serial turn so a queued request
        // cannot slip through before the poll thread marks the gate stopped.
        if owner_fd.is_some_and(owner_closed) {
            ordering.stop();
            ordering.leave(ticket);
            return;
        }
        let response = dispatch_with_terminal(&request, direct_terminal);
        ordering.leave(ticket);
        response
    };
    if let Ok(mut payload) = serde_json::to_vec(&response) {
        payload.push(b'\n');
        let _ = stream.write_all(&payload);
    }
}

fn owner_closed(owner_fd: RawFd) -> bool {
    let mut descriptor = libc::pollfd {
        fd: owner_fd,
        events: libc::POLLIN | libc::POLLHUP,
        revents: 0,
    };
    let ready = unsafe { libc::poll(&mut descriptor, 1, 0) };
    let closed_events = libc::POLLHUP | libc::POLLERR | libc::POLLNVAL;
    ready > 0 && descriptor.revents & closed_events != 0
}

#[derive(Default)]
struct OrderGate {
    next: AtomicU64,
    serving: Mutex<u64>,
    changed: Condvar,
    stopping: AtomicBool,
}

impl OrderGate {
    fn enter(&self) -> Option<u64> {
        if self.stopped() {
            return None;
        }
        let ticket = self.next.fetch_add(1, Ordering::SeqCst);
        let mut serving = self
            .serving
            .lock()
            .unwrap_or_else(|error| error.into_inner());
        while *serving != ticket && !self.stopped() {
            serving = self
                .changed
                .wait(serving)
                .unwrap_or_else(|error| error.into_inner());
        }
        (!self.stopped()).then_some(ticket)
    }

    fn leave(&self, ticket: u64) {
        let mut serving = self
            .serving
            .lock()
            .unwrap_or_else(|error| error.into_inner());
        if *serving == ticket {
            *serving += 1;
            self.changed.notify_all();
        }
    }

    fn stop(&self) {
        // Serialize the state transition with the predicate check in enter().
        // Without this lock, a waiter can observe `stopping == false`, lose the
        // notification just before Condvar::wait releases the mutex, and keep
        // an SSH-owned relay alive after its owner pipe closes.
        let _serving = self
            .serving
            .lock()
            .unwrap_or_else(|error| error.into_inner());
        self.stopping.store(true, Ordering::SeqCst);
        self.changed.notify_all();
    }

    fn stopped(&self) -> bool {
        self.stopping.load(Ordering::SeqCst)
    }
}

fn install_signal_handlers() -> io::Result<()> {
    unsafe extern "C" fn stop(_signal: libc::c_int) {
        LAST_SIGNAL.store(_signal, Ordering::SeqCst);
        STOPPING.store(true, Ordering::SeqCst);
        let descriptor = WAKE_WRITE.load(Ordering::SeqCst);
        if descriptor >= 0 {
            let byte = [0_u8; 1];
            let _ = unsafe { libc::write(descriptor, byte.as_ptr().cast(), 1) };
        }
    }

    let handler = stop as *const () as libc::sighandler_t;
    let previous_term = unsafe { libc::signal(libc::SIGTERM, handler) };
    let previous_int = unsafe { libc::signal(libc::SIGINT, handler) };
    if previous_term == libc::SIG_ERR || previous_int == libc::SIG_ERR {
        return Err(io::Error::last_os_error());
    }
    Ok(())
}

/// Remove only old owner-held relay sockets that no longer accept connections.
pub fn sweep() -> io::Result<()> {
    let now = SystemTime::now();
    let uid = unsafe { libc::getuid() };
    let runtime_base = std::env::var_os("XDG_RUNTIME_DIR")
        .filter(|value| Path::new(value).is_absolute())
        .map(PathBuf::from)
        .unwrap_or_else(std::env::temp_dir);
    let mut roots = vec![
        (PathBuf::from("/tmp"), "termnav-relay-"),
        (std::env::temp_dir(), "termnav-relay-"),
        (runtime_base.join(format!("termnav-{uid}")), "relay-"),
        // `private_socket_directory` uses this short owner-only root when a
        // macOS TMPDIR/XDG path cannot fit in sockaddr_un. Scan it without
        // creating it so a crash-only stale pathname is reclaimed on the next
        // connection just like a normal runtime-root socket.
        (PathBuf::from(format!("/tmp/termnav-{uid}")), "relay-"),
    ];
    roots.sort();
    roots.dedup();
    for (root, prefix) in roots {
        let Ok(entries) = fs::read_dir(root) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let Some(name) = path.file_name().and_then(|value| value.to_str()) else {
                continue;
            };
            if !name.starts_with(prefix) || !name.ends_with(".sock") {
                continue;
            }
            let Ok(metadata) = fs::symlink_metadata(&path) else {
                continue;
            };
            if !metadata.file_type().is_socket() || metadata.uid() != uid {
                continue;
            }
            let old = metadata
                .modified()
                .ok()
                .and_then(|modified| now.duration_since(modified).ok())
                .is_some_and(|age| age >= Duration::from_secs(60));
            if old && UnixStream::connect(&path).is_err() {
                let _ = fs::remove_file(path);
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::os::unix::fs::symlink;
    use std::os::unix::net::UnixListener;

    use serde_json::json;

    use super::{SocketPathGuard, dispatch, prepare_socket_path, wire_action, wire_scope};
    use crate::navigation::Action;

    #[test]
    fn invalid_protocol_objects_fail_closed() {
        assert_eq!(
            dispatch(&json!({"v": 1, "op": "navigate"})),
            json!({"v": 2, "result": "error"})
        );
        assert_eq!(
            dispatch(&json!({"v": 2, "op": "unknown"})),
            json!({"v": 2, "result": "error"})
        );
    }

    #[test]
    fn wire_vocabulary_is_action_specific() {
        assert_eq!(wire_scope(Action::PaneSelect), "pane");
        assert_eq!(wire_scope(Action::TabSelect), "window");
        assert_eq!(wire_scope(Action::TabMove), "move");
        assert!(wire_action("pane", "left").is_some());
        assert!(wire_action("pane", "next").is_none());
        assert!(wire_action("window", "previous").is_some());
        assert!(wire_action("move", "down").is_none());
    }

    #[test]
    fn socket_parent_rejects_a_symlinked_directory() {
        let root = std::env::temp_dir().join(format!(
            "termnav-socket-parent-{}-{}",
            std::process::id(),
            super::now_seconds()
        ));
        let target = root.join("target");
        let linked = root.join("linked");
        fs::create_dir_all(&target).expect("create target directory");
        symlink(&target, &linked).expect("create parent symlink");

        let error = prepare_socket_path(&linked.join("relay.sock"))
            .expect_err("symlinked socket parent must be rejected");

        assert_eq!(error.kind(), std::io::ErrorKind::PermissionDenied);
        assert!(!target.join("relay.sock").exists());
        fs::remove_dir_all(&root).expect("remove test directory");
    }

    #[test]
    fn post_bind_failure_guard_removes_the_socket_path() {
        let root = std::env::temp_dir().join(format!(
            "termnav-socket-guard-{}-{}",
            std::process::id(),
            super::now_seconds()
        ));
        fs::create_dir_all(&root).expect("create socket directory");
        let path = root.join("relay.sock");

        let listener = UnixListener::bind(&path).expect("bind test socket");
        let guard = SocketPathGuard::new(&path);
        assert!(path.exists());
        drop(listener);
        drop(guard);

        assert!(!path.exists());
        fs::remove_dir_all(&root).expect("remove test directory");
    }
}
