.TH WEZTERM-SELECT-PANE 1 "2026-08-12" "termnav" "User Commands"
.SH NAME
wezterm-select-pane \- request pane selection in a parent tmux layer
.SH SYNOPSIS
.B wezterm-select-pane
.B --parent
.RI { left | down | up | right }
.RI [ tty ]
.SH DESCRIPTION
.B wezterm-select-pane
emits a WezTerm OSC 1337
.B SetUserVar
request named
.B DOT_PARENT_SELECT_PANE
inside tmux passthrough framing. WezTerm can translate the request from a
remote nested tmux into a private key handled by its parent tmux layer.
.SH OPTIONS
.TP
.B --parent
Required. Route selection to the parent tmux layer.
.TP
.B --tty IttyR
Write the request to
.I tty
instead of
.B $WEZTERM_SELECT_PANE_TTY
or
.B /dev/tty .
.TP
.B -h, --help
Show command help.
.SH ARGUMENTS
.TP
.BR left , down , up , right
Direction of the adjacent pane to select.
.SH EXAMPLES
.nf
wezterm-select-pane --parent left /dev/ttys001
wezterm-select-pane --parent up --tty /dev/ttys001
.fi
.SH EXIT STATUS
.TP
.B 0
The request was written.
.TP
.B 2
Usage error.
.SH SEE ALSO
.BR wezterm-switch-tab (1),
.BR tmux (1)
